# Generated by Django 5.1.3 on 2024-11-15 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Название должно быть строковым значением', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')], verbose_name='Название')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
                ('grams_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Вес должен быть положительным числом')], verbose_name='Вес в граммах')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Название должно быть строковым значением', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')], verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Название должно быть строковым значением', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')], verbose_name='Название')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='Вес должен быть положительным числом')], verbose_name='Общий вес в граммах')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='Цена должна быть положительным числом')], verbose_name='Цена')),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe_catalog.measurementunit', verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецепте',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe_catalog.RecipeIngredient', to='recipe_catalog.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipes_ingredients'),
        ),
    ]
